core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' ),
    path('login', views.login, name='login' ),
    path('signup', views.signup, name='signup' ),
    path('shows/<str:movie_title>/', views.movie_detail, name='movie_detail'),
    path('watch/<str:content_type>/<str:movie_title>/', views.watch, name='watch'),
    path('serie/watch/<str:movie_title>/<int:season_pk>/',
         views.serie_watch_page, name='serie_watch_page'),
]

toon_stream/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('core.urls'))
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
import uuid

class Movie(models.Model):
    TYPE_CHOICE = [
       ('movie','Movie'),
       ('serie','Series'),
       ('special','Special')
    ]
    uu_id = models.UUIDField(default=uuid.uuid4)
    title = models.CharField(max_length=255)
    description = models.TextField()
    release_date = models.DateField()
    type = models.CharField(max_length=100,choices=TYPE_CHOICE,default='Movie')
    production_company = models.CharField(max_length=255,default='Uknown')
    length = models.PositiveIntegerField()
    image_card = models.ImageField(upload_to='movie_images/')
    image_cover = models.ImageField(upload_to='movie_images/')
    video = models.FileField(upload_to='movie_videos/')
    trailer_link = models.TextField()
    movie_views = models.IntegerField(default=0)
    is_series = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    

class Season(models.Model):
  movie = models.ForeignKey(
      Movie, on_delete=models.CASCADE)
  season_number = models.PositiveIntegerField()
  poster = models.ImageField(upload_to='season_posters/')
  episodes_count = models.PositiveIntegerField(default=0)

  def __str__(self):
    return f"Season {self.season_number} - {self.movie.title}"


class Episode(models.Model):
  season = models.ForeignKey(Season, on_delete=models.CASCADE)
  episode_number = models.PositiveIntegerField()
  episode = models.FileField(upload_to='episodes/')

  def __str__(self):
    return f"E{self.episode_number} - {self.season.movie.title} S{self.season.season_number}"

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User, auth
from django.contrib import messages
from .models import Movie, Season, Episode
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'index.html', context)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('login')

    return render(request, 'login.html')


def signup(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email already used')
                return redirect('signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username already used')
                return redirect('signup')
            else:
                user = User.objects.create_user(
                    username=username, email=email, password=password2)
                user.save()

                # log user in
                user_login = auth.authenticate(
                    username=username, password=password)
                auth.login(request, user_login)
                return redirect('/')
        else:
            messages.info(request, 'Passwords do not match')
            return redirect('signup')
    else:
        return render(request, 'signup.html')


@login_required
def movie_detail(request, movie_title):
    movie = get_object_or_404(Movie, title=movie_title)
    context = {
        'movie': movie,
    }

    return render(request, 'movie_detail.html', context)


@login_required
def watch(request, content_type, movie_title):
    movie = get_object_or_404(Movie, title=movie_title)
    context = {
        'movie': movie,
    }
    if content_type == 'movie':
        return render(request, 'watch_movie.html', context)

    elif content_type == 'serie':
        return render(request, 'watch_serie.html', context)

    if content_type == 'special':
        special = get_object_or_404(Movie, title=movie_title)
        special_episodes = special.special_episodes
        context = {
            'special': special,
            'special_episodes': special_episodes,
        }
        return render(request, 'watch_special.html', context)

    else:
        return render(request, 'index.html')


@login_required
def movie_watching(request, movie_title):
    movie = get_object_or_404(Movie, title=movie_title)
    context = {
        'movie': movie,
    }
    return render(request, 'watch_movie.html', context)


@login_required
def series_watching(request, movie_title):
    serie = get_object_or_404(Movie, title=movie_title)
    context = {
        'serie': serie,
    }
    return render(request, 'watch_serie.html', context)


def serie_watch_page(request, movie_title, season_pk):
    season = get_object_or_404(Season, pk=season_pk)
    movie = season.movie
    episodes = season.episode_set.all()  # Assuming episodes are related to Season

    context = {
        'season': season,
        'episodes': episodes,
        'movie': movie,
        'episode_videos': [episode.episode for episode in episodes],
        # Initial video URL
        'initial_video_url': episodes[0].episode.url if episodes else None,
    }
    return render(request, 'watch_serie.html', context)


def get_episode_video_url(episode_id):
    episode = get_object_or_404(Episode, pk=episode_id)
    return episode.episode.url

templates/genre.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="/">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/sciencefiction/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="search" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="/logout" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    
    <hr>

    <section class="py-10 px-5">
    
        <div align="center">
            <h2 class="text-xl mb-5">
                '{{movie_genre | title}}' Films
            </h2>
        </div>
        <div class="flex space-x-5 overflow-x-auto">

            {% for movie in movies %}
            <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
    </section>
    
   

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
        </div>
    </div>

    <script>
        function showModal(element) {
            // Retrieve data attributes
            const title = element.getAttribute('data-title');
            const description = element.getAttribute('data-description');
            const releaseDate = element.getAttribute('data-release-date');
            const genre = element.getAttribute('data-genre');
            const length = element.getAttribute('data-length');
            const imageCardUrl = element.getAttribute('data-image-card-url');
            const imageCoverUrl = element.getAttribute('data-image-cover-url');
            const dataVideoUrl = element.getAttribute('data-video-url');
        
            // Update the modal's content with the movie details
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;
        
            // Show the modal
            modal.style.display = 'block';
            setTimeout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }
        
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimeout(() => {
                modal.style.display = 'none';
            }, 300);
        }
        

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                hideModal();
            }
        }

        function addItemToList() {
            const modal = document.getElementById('movieModal')
            var movieID = modal.querySelector('.modal-content a').href;

            $.ajax({
                url: "{% url 'add-to-list' %}",
                type: "POST",
                data: {
                    movie_id: movieID,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);

                    $('#addToListButton').prop('disabled', true);

                    console.log("Item added to list!");
                },
                error: function(xhr, errmsg, err) {
                    
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
    </script>
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="/static/img/icon.ico">
    <title>ToonStream</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
    rel="stylesheet">
</head>

<body class=" text-white  max-h-screen  font-[Montserrat]" >
    <!-- background section -->
    <div class="absolute z-[-1] inset-0 bg-gradient-to-t from-[#000] to-[#0000]"></div>
    <div class="absolute z-[-2]  w-full h-1/4 bg-gradient-to-b from-[#00000086] to-[#0000]"></div>
    <img class="absolute z-[-3] inset-0 h-full w-full object-cover " src="{{movies.last.image_cover.url}}" alt="">
    <header class=" bg-gradient-to-b from-[#00000031] to-[#0000] ">
        <div class="container mx-auto p-5 flex justify-between items-center">
            <div class="flex justify-between items-center gap-10">
                <img class="h-10" src="../static/img/white_logo.png" alt="Netflix Logo">
                <nav class="flex space-x-5">
                    <span><a href="/">Home</a></span>
                    <span><a href="/my-list">Movies</a></span>
                    <span><a href="/my-list">My List</a></span>
                </nav>
            </div>
            
            
            <div class="flex space-x-5 items-center">
                <form action="search" method="POST">
                    {% csrf_token %}
                    <input type="search" name="search_term" placeholder="Search"
                        class="bg-black bg-opacity-50  backdrop-blur-lg py-2.5 pl-4 rounded-md mx-2 outline-none">
                    <button class="bg-purple-600 text-white py-2 px-3 rounded hover:bg-purple-500"><i
                            class='bx bx-search'></i></button>
                </form>
                <div class="relative max-w-10 h-full flex items-center">
                    <div class="flex-col items-center justify-center max-w-10 text-sm font-light leading-3">Welcome, <span
                            class="text-lg font-bold text-purple-600">{{user.username}}</span></div>
            
                </div>
            </div>
        </div>
    </header>
    <section class="container mx-auto relative flex py-20 flex-col space-y-10" style="background-image: url('{{featured_movie.image_cover.url}}'); background-size: cover; background-position: center;">
        <h2 class="text-6xl font-extrabold max-w-[40rem] drop-shadow">
            {{movies.last.title}}
        </h2>
        <div class="flex justify-start gap-5">
            <p class="opacity-90">{{movies.last.production_company}}</p>
            <p class="font-extrabold text-purple-600">{{movies.last.release_date|date:"Y"}}</p>
        </div>
        <div class="flex gap-5">
            <a href="{% url 'watch' content_type=movies.last.type movie_title=movies.last.title %}"><button class="px-14 py-3 rounded-full font-bold bg-purple-600 hover:bg-purple-500">PLAY</button></a>
            <button class="h-12 aspect-square border-2 rounded-full text-white hover:bg-white hover:text-black transition-color duration-150 ease-in-out"><i class='bx bx-plus font-light  text-2xl'></i></button>
        </div>
    </section>
    <h2 class="text-xl font-bold mb-5 container mx-auto">MY LIST</h2>
    <section
        class="fixed bottom-0 right-0 left-0 container mx-auto py-10 overflow-x-scroll" id="container">
    
        
    
        <div class="flex space-x-5 scrolling-content">
            {% for movie in movies %}
            <a href="{% url 'movie_detail' movie_title=movie.title %}">
                <div class="relative w-40 h-64 rounded-lg flex-shrink-0 film-card">
                    <div
                        class="absolute z-[1] text-sm top-2 right-2 px-2 py-1 bg-purple-700 bg-opacity-70 border shadow-lg border-[#ffffff3f] backdrop-blur-md rounded-md">
                        {{ movie.type }}
                    </div>
                    <img class="rounded-lg w-full h-full absolute inset-0 object-cover" src="{{ movie.image_card.url }}"
                        alt="">
                </div>
            </a>
            {% endfor %}
        </div>
    <style>
        .container::-webkit-scrollbar {
            
            display: none;
        }
    
        .container {
            -ms-overflow-style: none;
            
            scrollbar-width: none;
            
        }
    </style>
    </section>
    
    
    

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
            
        </div>
    </div>
</body>

</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/x-icon" href="/static/img/icon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/login.css' %}" />

    <title>Login</title>
</head>
<body>

    <div class="bg-image mx-auto flex justify-center items-center">
        <div class="min-w-[30rem] flex flex-col bg-[#190F25] transition-all duration-100 ease-in bg-opacity-80 backdrop-blur-lg rounded-lg p-8">
            <h1 class="text-white text-xl pb-5 font-bold text-center ">Login</h1>
            <div class="h-0.5 mb-5 w-full bg-gray-400 opacity-10 rounded-full"></div>

            <div class="py-2">
                {% for message in messages %}
                <h5 class="font-bold text-red-600 text-center">{{message}}</h5>
                {% endfor %}
            </div>


            <form class="flex flex-col gap-6 pb-8" action="" method="POST">
                {% csrf_token %}
                <input class="bg-black bg-opacity-40  backdrop-blur-lg py-3 pl-4 border-none outline-none text-white rounded-md" type="text" name="username" placeholder="Username" />
                <input class="bg-black bg-opacity-40  backdrop-blur-lg py-3 pl-4 border-none outline-none text-white rounded-md" type="password" name="password" placeholder="Password" />
                <button class="bg-purple-600 py-3 rounded-md font-bold uppercase" style="color:white" type="submit" class="signup-btn">Login</button>
            </form>
            <div class="h-0.5 mb-5 w-full bg-gray-400 opacity-10 rounded-full"></div>
            <div class="help-text" align="center">
                <span class="text-purple-600 mt-5">Dont have an account? <a class="font-bold" href="signup">Signup</a></span>
            </div>
        </div>
    </div>

</body>
</html>

templates/movie.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Playback</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-blue-900 text-white" style="background-color: #181818;">

    <!-- Navbar -->
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        <nav class="flex space-x-5">
            <span>Home</span>
            <span>Series</span>
            <span>Films</span>
            <span>New & Popular</span>
        </nav>
        <div class="flex space-x-5 items-center">
            <input type="search" placeholder="Search" class="bg-gray-700 p-2 rounded">
            <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            <div class="relative">
                <a href="#" class="block p-2">Logout</a>
            </div>
        </div>
    </header>

    <hr>
    <!-- Main Content -->
    <div class="container mx-auto mt-10">
        <!-- Movie Title and Back Button -->
        <div class="flex items-center justify-between">
            <h2 class="text-3xl font-semibold">{{movie_details.title}}</h2>
            <a href="/" class="text-gray-400 hover:text-white">← Back to movies</a>
        </div>

        <div class="mt-8">
            <video class="w-full h-auto" controls>
                <source src="{{movie_details.video.url}}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>


        <!-- Movie Description -->
        <div class="mt-6">
            <h3 class="text-xl font-semibold mb-2">About the Movie</h3>
            <p>
                {{movie_details.description}}
            </p>
        </div>
    </div>

</body>

</html>

templates/movie_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="/static/img/icon.ico">
    <title>{{movie.title}}</title>
<script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
    rel="stylesheet">
</head>

<body class="px-20 text-white flex flex-col h-[120vh] xl:h-full min-h-screen font-[Montserrat] overflow-x-hidden">
    
    <div class="absolute z-[-1] inset-0 h-[120vh] xl:h-full min-h-screen bg-gradient-to-r from-[#000] to-[#0000]"></div>
    {% if movie.image_cover %}
    <img class="absolute z-[-2] h-[120vh] xl:h-full min-h-screen w-full inset-0 object-cover " src='{{movie.image_cover.url}}' alt="">
    {% else %}
    <p>No image available</p>
    {% endif %}
    <!-- Navbar -->
    <header class="py-10 ">
    
        <a href="/" class="flex gap-4 items-center group "><i
                class='bx bx-arrow-back group-hover:-translate-x-3 transition-all duration-200 ease-in-out'></i>
            <span>Return
                to Home Page</span></a>
    </header>

    <!-- content section -->
    <section class="flex-col justify-center items-start gap-10 h-full">
        <div class="flex flex-col gap-20 xl:flex-row xl:gap:0 xl:justify-between items-center h-full">
            <section class="flex justify-start items-start gap-8 w-full">
                <div class="h-[27rem] ">
                    <img class="h-full rounded-lg object-cover" src="{{movie.image_card.url}}" alt="">
                </div>
                <div class="flex flex-col gap-5">
                    <div class="flex gap-3">
                        <div class="font-semibold bg-purple-600 w-max px-3 py-1 rounded capitalize">{{movie.type}}</div>
                        <div class="font-semibold bg-purple-600 w-max px-3 py-1 rounded "> {{ movie.length }}
                            {% if movie.type == 'movie' %}
                            Hours
                            {% elif movie.type == 'serie' %}
                            Seasons
                            {% elif movie.type == 'special' %}
                            Episodes
                            {% endif %} </div>
                        <div class="font-semibold bg-purple-600 w-max px-3 py-1 rounded capitalize">
                            {{movie.release_date|date:"Y"}}</div>
                    </div>
        
                    <h2 class="text-6xl font-extrabold max-w-[30rem]">{{movie.title}}</h2>
                    <h3 class="text-sm text-gray-200">{{movie.production_company}}</h3>
                    <p class="max-w-[30rem]">{{movie.description}}</p>
                    
                    <a href="{% url 'watch' content_type=movie.type movie_title=movie.title %}">
                        <button class="uppercase rounded-full font-bold bg-purple-600 hover:bg-purple-500 transition-colors duration-150 ease-in-out w-max px-5 py-3 flex items-center gap-3">
                            <i class='bx bx-play text-3xl'></i>Watch Now</button>
                    </a>
                    <div class="flex items-center gap-2">
                        <i class='bx bx-show'></i>
                        <span>{{movie.movie_views}}</span>
                    </div>

                </div>
        
            </section>
        
            <section class="w-full flex justify-center items-center mx-auto rounded-lg">
                <div class="flex justify-center w-full rounded-lg">
                    <iframe src='{{movie.trailer_link}}' title="YouTube video player" frameBorder="0" " allowFullScreen
                                class=" w-3/4 mx-auto h-full aspect-video rounded-lg"></iframe>
                </div>
            </section>
        </div>
        <div class="h-full">
            {% if movie.is_series %}
            <h2 class="py-8 text-xl font-bold">Seasons</h2>
            <ul class="seasons-list flex space-x-5">
                {% for season in movie.season_set.all %}
                <li class="season-item relative w-40 h-64 rounded-lg  film-card">
                    <a href="{% url 'serie_watch_page' movie.title season.pk %}">
                        <img src="{{ season.poster.url }}" class="rounded-lg w-full h-full absolute inset-0 object-cover"
                            alt="Season {{ season.season_number }} Poster">
                        <div
                            class="absolute z-[1] text-sm top-2 right-2 px-2 py-1 bg-purple-700 bg-opacity-70 border shadow-lg border-[#ffffff3f] backdrop-blur-md rounded-md">
                            S {{ season.season_number }}</div>
                    </a>
                </li>
                {% endfor %}
            </ul>
            {% elif movie.is_special %}
            <a href="{% url 'watch_special.html' %}">
                <button class="py-2 px-4 rounded-lg bg-purple-600 hover:bg-purple-500 text-white">Watch Special</button>
            </a>
            {% endif %}
        </div>
    </section>



</body>

</html>